title: Gut Feeling Blog with Zach
description: > # this means to ignore newlines until "baseurl:"
  I am a guy in my 20s trying to find fulfillment in my life turned upside down by chronic illness.
  I invite you to join me on this journey as the universe teaches me empathy for the chronically ill,
  the hard way.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gutfeelingblog.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: gutfeelingblog #if your site has a twitter account, enter it here

# Author Settings
author: Zachary Baker # add your name
author-img: author-thumb.jpg # add your photo
about-author: I am a guy in my 20s trying to find fulfillment in my life turned upside down by chronic illness. Immediately after graduating from college, my physical and mental health took a huge dive. Over the next few years I would experience crippling panic attacks, debilitating depression and anxiety, DP/DR, insomnia, major digestive issues, and the constantly nagging question of whether I would be able to live a normal life as I had planned. I invite you to join me on this journey as the universe teaches me empathy for the chronically ill, the hard way.
twitter: gutfeelingblog # add your Twitter handle
#facebook: # add your Facebook handle
#github: # add your Github handle
#linkedin: # add your Linkedin handle
email: gutfeelingblog@gmail.com # add your Email address

# Disqus
discus-identifier: gutfeelingblog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
